export const GET_COLLEGE_LIST = "GET_COLLEGE_LIST";
export const SUCCESS_COLLEGE_LIST = "SUCCESS_COLLEGE_LIST";
export const FAILURE_COLLEGE_LIST = "FAILURE_COLLEGE_LIST";

export const GET_UNIVERSITY_COURSE_LIST = "GET_UNIVERSITY_COURSE_LIST";
export const SUCCESS_UNIVERSITY_COURSE_LIST = "SUCCESS_UNIVERSITY_COURSE_LIST";
export const FAILURE_UNIVERSITY_COURSE_LIST = "FAILURE_UNIVERSITY_COURSE_LIST";

export const GET_COLLEGE_FOR_SELECTED_COURSE = "GET_COLLEGE_FOR_SELECTED_COURSE";
export const SUCCESS_COLLEGE_FOR_SELECTED_COURSE = "SUCCESS_COLLEGE_FOR_SELECTED_COURSE";
export const FAILURE_COLLEGE_FOR_SELECTED_COURSE = "FAILURE_COLLEGE_FOR_SELECTED_COURSE";